-- TABLE
CREATE TABLE pessoa (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,nome VARCHAR (80) NOT NULL,idade INTEGER NOT NULL,cpf VARCHAR (50) NOT NULL,RG VARCHAR (50) NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
 
-- INDEX
 
-- TRIGGER
 
-- VIEW
 
